spring-boot-template:
  nameOverride: "spring-boot-template"
  fullnameOverride: "spring-boot-template"
  replicaCount: 1
  image:
    repository: 703671900078.dkr.ecr.us-east-1.amazonaws.com/spring-boot-template
    tag: 0.4.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
    DB_URL: "jdbc:postgresql://unir-tfm-postgres-prod.c0li4ko84rxt.us-east-1.rds.amazonaws.com:5432/spring-boot-template-prod"
    DB_USERNAME: "spring-boot-template-prod"
  secrets:
    enabled: true
    secretName: "spring-boot-template-secret"
    data:
      DB_PASSWORD: "spring-boot-template-prod"
