name: "Create Application PR"
on:
  issues:
    types: [opened, reopened]

jobs:
  extract_info:
    name: Extract Issue Information
    if: contains(github.event.issue.labels.*.name, 'new-app')
    runs-on: ubuntu-latest
    outputs:
      application-name: ${{ steps.extract_info.outputs.APPLICATION_NAME }}
      repository-name: ${{ steps.extract_info.outputs.REPOSITORY_NAME }}
      environment: ${{ steps.extract_info.outputs.ENVIRONMENT }}
      helm_chart_name: ${{ steps.extract_info.outputs.HELM_CHART_NAME }}
      helm_path: ${{ steps.extract_info.outputs.HELM_PATH }}
      app_version: ${{ steps.extract_info.outputs.APP_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Parse Issue Body
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo "$ISSUE_BODY" > issue_body.md
          python scripts/extract-app-info.py issue_body.md

      - name: Extract Repo Information
        id: extract_info
        run: |
          echo "APPLICATION_NAME=$(grep 'Application Name:' extracted_info.txt | cut -d':' -f2- | xargs)" >> $GITHUB_OUTPUT
          echo "REPOSITORY_NAME=$(grep 'Repository Name:' extracted_info.txt | cut -d':' -f2- | xargs)" >> $GITHUB_OUTPUT
          echo "HELM_CHART_NAME=$(grep 'Helm Chart Name:' extracted_info.txt | cut -d':' -f2- | xargs)" >> $GITHUB_OUTPUT
          echo "HELM_PATH=$(grep 'Helm Path:' extracted_info.txt | cut -d':' -f2- | xargs)" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$(grep 'Application Version:' extracted_info.txt | cut -d':' -f2- | xargs)" >> $GITHUB_OUTPUT
          echo "ENVIRONMENT=$(grep 'Environment:' extracted_info.txt | cut -d':' -f2- | xargs)" >> $GITHUB_OUTPUT

      - name: Print Extracted Information
        run: |
          echo "Application Name: ${{ steps.extract_info.outputs.APPLICATION_NAME }}"
          echo "Repository Name: ${{ steps.extract_info.outputs.REPOSITORY_NAME }}"
          echo "Helm Chart Name: ${{ steps.extract_info.outputs.HELM_CHART_NAME }}"
          echo "Helm Path: ${{ steps.extract_info.outputs.HELM_PATH }}"
          echo "Application Version: ${{ steps.extract_info.outputs.APP_VERSION }}"
          echo "Environment: ${{ steps.extract_info.outputs.ENVIRONMENT }}"

  argo-app-test-changes:
    name: Argo App Test Changes
    if: ${{ needs.extract_info.outputs.environment == 'test' || needs.extract_info.outputs.environment == 'both' }}
    needs: [extract_info]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Token From GitHub APP
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.UNIR_TFM_APP_ID }}
          private-key: ${{ secrets.UNIR_TFM_APP_PRIVATE_KEY }}
          repositories: "eks-workloads"

      - name: Modify values.yaml for Test Environment
        run: |
          # Generate the application name for test environment
          APP_NAME="${{ needs.extract_info.outputs.application-name }}-test"

          # Use yq to add the new application configuration
          yq eval ".applications.$APP_NAME = {\"project\": \"default\", \"source\": {\"path\": \"${{ needs.extract_info.outputs.HELM_PATH }}\"}, \"destination\": {\"namespace\": \"test\"}}" -i environments/test/configuration/values.yaml

      - name: Commit changes
        env:
          NAME: ${{ needs.extract_info.outputs.application-name }}
        run: |
          git config --global user.email "unir-tfm-devops[bot]@users.noreply.github.com"
          git config --global user.name "unir-tfm-devops[bot]"
          git remote set-url origin https://x-access-token:${{ steps.get_token.outputs.token }}@github.com/${{ github.repository }}
          git checkout -b feature/new-application-${{ env.NAME }}-test
          git add environments/test/configuration/values.yaml
          git commit -m "Modify environments/test/configuration/values.yaml"
          git push origin feature/new-application-${{ env.NAME }}-test
