name: "Plan ArgoCD Applications"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "environments/test/configuration/values.yaml"
      - "environments/prod/configuration/values.yaml"
      - "terraform/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  plan-changes:
    name: "Plan Changes"
    uses: unir-tfm-devops/reusable-github-actions/.github/workflows/terraform-plan-aws.yml@main
    with:
      working_directory: terraform
    secrets: inherit
